name: 'tuva_medicare_claims_connector'
version: '1.0.0'
config-version: 2

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  tuva_medicare_cclf_connector:
    +materialized: view
  # TODO is this required?
  # core:
  #  +materialized: table

vars:
  # TODO audit all variables - many may no longer be needed
  source_name: cclf                     # configuration required
                                        # name describing the dataset feeding this project

  input_database: medicare_claims       # configuration required
                                        # name of the database where sources feeding this project are stored

  input_schema:  cclf                   # configuration required
                                        # name of the schema where sources feeding this project is stored

  output_database: tuva                 # configuration required
                                        # name of the database where output of this project should be written

  output_schema: claims_input           # configuration required
                                        # name of the schema where output of this project should be written

  beneficiary_demographics: "{{ source(var('source_name'),'beneficiary_demographics') }}"
  parta_claims_header: "{{ source(var('source_name'),'parta_claims_header') }}"
  parta_claims_revenue_center_detail: "{{ source(var('source_name'),'parta_claims_revenue_center_detail') }}"
  parta_diagnosis_code: "{{ source(var('source_name'),'parta_diagnosis_code') }}"
  parta_procedure_code: "{{ source(var('source_name'),'parta_procedure_code') }}"
  partb_physicians: "{{ source(var('source_name'),'partb_physicians') }}"
  partb_dme: "{{ source(var('source_name'),'partb_dme') }}"

