version: 2

sources:
  - name: "{{ var('source_name') }}"
    database: "{{ var('source_database') }}"
    schema:  "{{ var('source_schema') }}"
    tables:
      - name: partb_dme
      - name: parta_claims_header
      - name: parta_diagnosis_code
      - name: parta_claims_revenue_center_detail
      - name: beneficiary_demographics
      - name: partb_physicians
      - name: parta_procedure_code