version: 2

sources:
  - name: cclf
    database: "{{ var('tuva_medicare_cclf_connector_database', 'medicare_claims') }}"
    schema:  "{{ var('tuva_medicare_cclf_connector_schema', 'cclf') }}"
    tables:
      - name: partb_dme
        identifier: "{{ var('tuva_medicare_cclf_connector_partb_dme_table_name', 'partb_dme') }}"
      - name: parta_claims_header
        identifier: "{{ var('tuva_medicare_cclf_connector_parta_claims_header_table_name', 'parta_claims_header') }}"
      - name: parta_diagnosis_code
        identifier: "{{ var('tuva_medicare_cclf_connector_parta_diagnosis_code_table_name', 'parta_diagnosis_code') }}"
      - name: parta_claims_revenue_center_detail
        identifier: "{{ var('tuva_medicare_cclf_connector_parta_claims_revenue_center_detail_table_name', 'parta_claims_revenue_center_detail') }}"
      - name: beneficiary_demographics
        identifier: "{{ var('tuva_medicare_cclf_connector_beneficiary_demographics_table_name', 'beneficiary_demographics') }}"
      - name: partb_physicians
        identifier: "{{ var('tuva_medicare_cclf_connector_partb_physicians_table_name', 'partb_physicians') }}"
      - name: parta_procedure_code
        identifier: "{{ var('tuva_medicare_cclf_connector_parta_procedure_code_table_name', 'parta_procedure_code') }}"